run:
  save_model: True

data:
  split_no: 333333
  dataset: Houston
  root: './data'
  split: semi-public

  val_samples_per_class: 0.2
  ood_left_out_classes: [3,]
  # test_samples_per_class: 1.0
  

model:
  seed: 112442562
  init_no: 1
  model_name: GCN
  hidden_dim: 256
  drop_prob: 0.5

training:
  epochs: 2000
  stopping_patience: 50
  stopping_metric: val_CE
  lr: 0.01
  weight_decay: 0.00001