run:
  save_model: True

data:
  split_no: 333333
  dataset: KSC
  root: './data'
  split: random
  train_samples_per_class: 20
  val_samples_per_class: 0.15
  test_samples_per_class: 0.8
  ood_left_out_classes: [10,]

model:
  seed: 112442562
  init_no: 1
  model_name: GCN
  hidden_dim: 128
  drop_prob: 0.5

training:
  epochs: 2000
  stopping_patience: 50
  stopping_metric: val_CE
  lr: 0.001
  weight_decay: 0.00001