run:
  save_model: False

data:
  split_no: 333333
  dataset: KSC
  root: './data'
  split: random
  train_samples_per_class: 20
  val_samples_per_class: 0.15
  test_samples_per_class: 0.8


model:
  seed: 1112222
  init_no: 1
  # GCN, GCNExp, GCNExpProp
  model_name: GPN
  hidden_dim: 64
  drop_prob: 0.5
  reduction: mean

  latent_dim: 10
  radial_layers: 10
  pretrain_mode: flow

  iteration_step: 10
  teleport: 0.2

  # emse_loss_weight: 0
  uce_loss_weight: 1
  # uce_log_loss_weight: 0
  # ce_loss_weight: 1
  # entropy_reg_weight: 0
  # # probability_teacher_weight: 0.001.
  # alpha_teacher_weight: 0
  reconstruction_reg_weight: 0
  tv_alpha_reg_weight: 0
  tv_vacuity_reg_weight: 0

training:
  epochs: 5000
  stopping_patience: 30
  stopping_metric: val_CE
  lr: 0.001
  weight_decay: 0.0005

  warmup_epochs: 5